// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ET79dgYsbIWwgJHeseSvSP8IK224zFU',
    appId: '1:216130914782:web:d31bceea25fbd377d4354f',
    messagingSenderId: '216130914782',
    projectId: 'ayn-raqeeb',
    authDomain: 'ayn-raqeeb.firebaseapp.com',
    storageBucket: 'ayn-raqeeb.firebasestorage.app',
    measurementId: 'G-543EKGZWGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkHG09VnVKoNDlI_A1Rhwva3d5sMOxAaw',
    appId: '1:216130914782:android:5c41881579856444d4354f',
    messagingSenderId: '216130914782',
    projectId: 'ayn-raqeeb',
    storageBucket: 'ayn-raqeeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxLEMbk1FPQ7O7nbfhKakrJzhyCybXm4',
    appId: '1:216130914782:ios:380b23970c4c3d46d4354f',
    messagingSenderId: '216130914782',
    projectId: 'ayn-raqeeb',
    storageBucket: 'ayn-raqeeb.firebasestorage.app',
    iosBundleId: 'com.example.aynRaqeebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxLEMbk1FPQ7O7nbfhKakrJzhyCybXm4',
    appId: '1:216130914782:ios:380b23970c4c3d46d4354f',
    messagingSenderId: '216130914782',
    projectId: 'ayn-raqeeb',
    storageBucket: 'ayn-raqeeb.firebasestorage.app',
    iosBundleId: 'com.example.aynRaqeebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ET79dgYsbIWwgJHeseSvSP8IK224zFU',
    appId: '1:216130914782:web:db5096ae87e06887d4354f',
    messagingSenderId: '216130914782',
    projectId: 'ayn-raqeeb',
    authDomain: 'ayn-raqeeb.firebaseapp.com',
    storageBucket: 'ayn-raqeeb.firebasestorage.app',
    measurementId: 'G-HTM5745GNL',
  );
}
